image: docker:latest
services:
  - docker:dind

stages:
  - build
  - deploy

before_script:
  - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"

build:
  stage: build
  script:
    - docker build -t docker-doxygen:latest .

deploy:
  stage: deploy
  script:
    - docker push "$CI_REGISTRY_IMAGE":latest
